### ISSUE TITLE
Few Queries

### ISSUE THREAD

**Issue by gitcoolcorner** [freyastreamlit/streamlit-lightweight-charts-ntf#46]
Few questions with respect to this repo:

1. The setting of scaleMargins do not work in this script?
2. I tried volume to be plotted to pane:0 and tried priceScaleID: "" and then I tried to set scaleMargins such that we can have both prices and volume in the same pane, but seems like it does not work, however, it worked fine in https://jsfiddle.net/adrianntf/6qea5ytv/
3. Is there a way we can make the subscribeCrosshairMove, either we display the value within the html chart element or anywhere on the streamlit via text possible?
4. As far as I know there is no way we can save the settings of pane size, is this correct?

**Comment by freyastreamlit** [comment]
Hi @gitcoolcorner 

Javascript-land, Python-land (and in this case Streamlit-land) == very very different. Streamlit does a great job in bridging the gap, but it is through containerisation - every element is contained and rendered separately, and there is "some"communication between them and Python. Features that you are referring to will require to have access and interact with the Javascript object itself (e.g. `subscribeCrosshairMove` - anything that happen in Javascript-land

This streamlit-component is a `one-way` wrapper - grabs all settings and sends in JSON format to React (Javascript-land), then React renders `lightweight-charts` with those settings and sends HTML/Javascript back. Python cannot interact with Javascript (and vice-versa) - different environments - we can send text/JSON etcetera between them but, that is it.

Javascript: I did mention the VueJS integration, but maybe you don't need that, in the README there are few links to DeKay's Youtube tutorials, maybe is a good fit...

- [GitHub](https://github.com/karthik947/PlotIndicators)
- [Youtube #1](https://www.youtube.com/watch?v=NlHjhmIe1EI)
- [Youtube #2](https://www.youtube.com/watch?v=2nxj4aLBhgo)

**Regarding items 1 and 2 - let me have a look - it should work (haven't tested).**

Best,

Joe

**Comment by gitcoolcorner** [comment]
I am able to plot the indicators/data etc from my DB to ST. Very easy to do compared to JS :)

![2023-06-15_22-42-17](https://github.com/freyastreamlit/streamlit-lightweight-charts-ntf/assets/135973158/3d3dfd71-969b-41eb-8910-07f887aac1d8)

Only thing that this is lacking now is the realtime update (using updateData) of the last bar, which I was able to do it with TV lightweight JS charts (with a lot of help of chatGPT) using v3.6-dev, but that JS script got complicated/convoluted that I cannot modify the script anymore (as I do not understand JS world and GPT forgets the context due to length).

I will continue to explore the TV Vue repo, once I understand some basics of Vue/NodeJS etc, I will revisit that repo and check it out.

Meanwhile if I want to use the updateData method of TV lightweight, how do I do that?

I understand Streamlit is not made for realtime apps and it refreshes the entire page, I am anyway thinking to refresh the page every 10/20 seconds to get latest data, either I could use updateData method or I would refresh the full page.

Thanks! Appreciate your help.

**Comment by freyastreamlit** [comment]
HI @gitcoolcorner 

Glad that is progressing - yes Streamlit will refresh the full page every time - there some tricks for caching but that I don't think it will apply for your scenario

I can confirm that item 1 and 2 - `scaleMargins` - are working as it should in the `ntf` repo (this one that uses the fork)

Have a look on the examples for the [Overlaid Charts](https://freyastreamlit-streamlit-lightw-examplespricevolumechart-j8ldyo.streamlit.app/) and [Overlaid Series with Markers](https://freyastreamlit-streamlit-ligh-examplesoverlaidareaschart-3pg5tr.streamlit.app/) on the main repo:

- https://github.com/freyastreamlit/streamlit-lightweight-charts

e.g.
```
"rightPriceScale": {
        "scaleMargins": {
	        "top": 0.2,
	        "bottom": 0.25,
        },
        "borderVisible": False,
},
"overlayPriceScales": {
        "scaleMargins": {
                  "top": 0.7,
                  "bottom": 0,
        }
},
```

**Comment by gitcoolcorner** [comment]
Okay, will check these settings, seems like they have to be inside rightPriceScale or overlayPriceScales in 4.0, this is how I had in v3.6Dev and worked fine:

const candlestickSeriesPriceScaleOptions = () => ({
  autoScale: true,
  scaleMargins: {
    top: 0.05,
    bottom: 0.2,
  },
});

const getVolumeSeriesOptions = () => ({
  priceScaleId: "",
  scaleMargins: {
    top: 0.82,
    bottom: 0,
  },
});

Last question:

Is there any way we can get the subscribeCrosshairMove on streamlit, not getting any data out from JS (did not know that is impossible earlier) back to streamlit, but while configuring itself we set this to display inside the chart element?

Thanks again for all the prompt help. Appreciate it.

**Comment by gitcoolcorner** [comment]
BTW, Tried this today and it works!:

`    col1, col2 = st.columns(2)

    with col1:
        renderLightweightCharts([
            {
                "chart": chartMultipaneOptions[0],
                "series": seriesMultipaneChart
            }
        ], 'multipane1')

    with col2:
        renderLightweightCharts([
            {
                "chart": chartMultipaneOptions[0],
                "series": seriesMultipaneChart
            }
        ], 'multipane2')

`

![2023-06-16_13-09-10](https://github.com/freyastreamlit/streamlit-lightweight-charts-ntf/assets/135973158/479549b8-67f8-4d22-8e69-51ba3ee44c1c)

I could not have done this on pure JS for sure, would have taken a zillion years + my script would be all messy by then.

**Comment by freyastreamlit** [comment]
Hi @gitcoolcorner 

- Is there any way we can get the subscribeCrosshairMove on streamlit: **Nope.**

Streamlit is outstanding for data science - I would keep things separate (well, I do)
Evaluating strategies and data science is a mindset different from operational trading - one is to think, the other is to act.
The technology to manage `datafeed streaming` is a big challenge on itself, and it needs proper resourcing - trading platforms are the specialised tools that resolve that - they have huge infrastructure (and costs) behind that

Closing this ticket

Best for your endeavours

Joe
