### ISSUE TITLE
streamlit deploy error

### ISSUE THREAD

**Issue by timesavingbee** [freyastreamlit/streamlit-lightweight-charts-ntf#49]
Hello.
I tried to deploy streamlit-lightweight-charts-ntf multi pane sample, but I got an error as following.

File "/mount/src/macro/streamlit_app.py", line 2, in <module>
    from streamlit_lightweight_charts_ntf import renderLightweightCharts

Even though I added requirement.txt as following.
streamlit-lightweight-charts-ntf

Please let me know how to solve this issue.

**Comment by freyastreamlit** [comment]
@timesavingbee 

The error says that you don't have the package(s) installed on your machine
Not sure your experience with python, so lets cover possibilities:

Are you installing the 'requirements..txt' file with: `pip install -r requirements.txt`

Another possibility is that you have multiple python installs on your machine (typical for MACs) - so make sure you install for the correct version - `python --version`.
We do need python 3 - so check if you can run `python3` and if so:

`python3 -m pip install streamlit-lightweight-charts-ntf` or
`pip3 install streamlit-lightweight-charts-ntf`

And let me know which OS machine are you using

Best,

Joe

**Comment by timesavingbee** [comment]
> @timesavingbee
> 
> The error says that you don't have the package(s) installed on your machine Not sure your experience with python, so lets cover possibilities:
> 
> Are you installing the 'requirements..txt' file with: `pip install -r requirements.txt`
> 
> Another possibility is that you have multiple python installs on your machine (typical for MACs) - so make sure you install for the correct version - `python --version`. We do need python 3 - so check if you can run `python3` and if so:
> 
> `python3 -m pip install streamlit-lightweight-charts-ntf` or `pip3 install streamlit-lightweight-charts-ntf`
> 
> And let me know which OS machine are you using
> 
> Best,
> 
> Joe

Thank you so much, it works well.
As I am a python beginner, I didn't know well how to make requirements.txt properly.
