### ISSUE TITLE
Can I put titles in each panes?

### ISSUE THREAD

**Issue by junikim95** [freyastreamlit/streamlit-lightweight-charts-ntf#50]
I tried to write titles in each panes such as price, volume, MACD, RSI and so on, but I didn't find any solution.
Water mark is available but it affects all panes as same.
Could you let me know how to write titles in each panes?

**Comment by freyastreamlit** [comment]
@junikim95 

Very sorry, just noticed this comment - nope, we can't - yjos 'ntf; version allows to sync the 'hair-cross' (mouse movements) between panes. I guess it could could a reason why this patch wasn't adopted by the lightweight-charts team - but their plug-ins strategy on v4 doesn't resolve teh synchronisation (although it works fine on tradingview)

Very sorry for the delay

Best,

Joe Rosa
