### ISSUE TITLE
Pane divider can be adjusted by default?

### ISSUE THREAD

**Issue by junikim95** [freyastreamlit/streamlit-lightweight-charts-ntf#51]
Hello,
Is there any option to adjust pane divider such as between candle chart and volume?
I know users can change the height of each panes with mouse click and move up/down the divider between two panes.
But I want to set it initially as a default not using mouse action.
Please let me know how to handle it. Thanks in advance~!

**Comment by freyastreamlit** [comment]
@junikim95 

Nope, no setup for that. maybe an extra height on pane-height could help the visual
This is a frozen branch that never was adopted by the lightweight charts team - it is as it is - although is what we mainly use for our financial charts studies in-house

Best,

Joe
